### ISSUE TITLE
Updating

### ISSUE THREAD

**Issue by Berndinox** [sdelrio/consul#1]
Hy,

i've the following config:

```
  consul:
    image: sdelrio/consul
    labels: [app=consul]
    environment:
      - 'CONSUL_LOCAL_CONFIG={"skip_leave_on_interrupt": true}'
      - CONSUL_BIND_INTERFACE=eth0
      - CONSUL=consul
      - CONSUL_CHECK_LEADER=false
    deploy:
      replicas: 3
      placement:
        constraints: [node.role == manager]
      update_config:
        parallelism: 1
        delay: 30s
        monitor: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 60s
```
The Problem is only while updating the stack, it throws about 200 errors, some of them:

"agent failed to sync no cluster leader"
"REQUEST PUT /v1/sessions/renew.."

May there is a way to suppress those messages while updating?
